### PR TITLE
[Macros] Introduce macro specification in assertMacroExpansion

### LINKED ISSUE #2031: assertMacroExpansion always passes empty array as `conformingTo` parameter of extension macros
### Description

Previously a bug with conformance macros:

- https://github.com/apple/swift-syntax/issues/1742
- https://github.com/apple/swift-syntax/pull/1773
- https://github.com/apple/swift-syntax/issues/1801

This issue has regressed with the change to extension macros.

### Steps to Reproduce

1. Write a macro expansion test for an extension macro.
2. Note that the expanded source does not include the extension.

### PR DESCRIPTION
**Pull request by soumyamahunt**
Resolves #2031.

Implements fixes suggested by @DougGregor.

Allows testing extension macros completely.

### CODE REVIEW

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 1]
```diff
@@ -254,13 +254,17 @@ func assertDiagnostic(
 ///   - macros: The macros that should be expanded, provided as a dictionary
 ///     mapping macro names (e.g., `"stringify"`) to implementation types
 ///     (e.g., `StringifyMacro.self`).
+///   - conformanceMap: The protocols that maco should conform to, provided as
```
Comment (mackoj) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:257]:
```suggestion
///   - conformanceMap: The protocols that macro should conform to, provided as
```

File: Tests/SwiftSyntaxMacroExpansionTest/ExtensionMacroTests.swift [hunk 2]
```diff
@@ -128,4 +128,87 @@ final class ExtensionMacroTests: XCTestCase {
...
+        }
+      }
+      """,
+      expandedSource: """
+        struct Wrapper {
+          struct MyType {
+          }
+        }
+
+        extension MyType: Encodable {
```
Comment (mackoj) [inline Tests/SwiftSyntaxMacroExpansionTest/ExtensionMacroTests.swift:188]:
```suggestion
        extension Wrapper.MyType: Encodable {
```

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 3]
```diff
@@ -254,13 +254,17 @@ func assertDiagnostic(
...
+///     a dictionary mapping macro names (e.g., `"AddCodable"`) to protocols names
+///     (e.g., `"Decodable"`, `"Encodable"` etc.).
 ///   - testModuleName: The name of the test module to use.
 ///   - testFileName: The name of the test file name to use.
 public func assertMacroExpansion(
   _ originalSource: String,
   expandedSource expectedExpandedSource: String,
   diagnostics: [DiagnosticSpec] = [],
   macros: [String: Macro.Type],
+  conformsTo conformanceMap: [String: [TypeSyntax]] = [:],
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: I’m not a fan of adding another parameter to `assertMacroExpansion`. What I would prefer is that the `macros` parameter becomes `[String: MacroSpec]` with 

```swift
struct MacroSpec {
  let type: MacroType
  let conformances: [TypeSyntax]
}
```

The benefit of that is that we could expand `MacroSpec` in the future without the need to have more parameters to `assertMacroExpansion`.

We still need to keep the current function that takes `macros: [String: Macro.Type]` around for API-compatibility.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 4]
```diff
@@ -23,6 +23,7 @@ extension SyntaxProtocol {
   /// Expand all uses of the given set of macros within this syntax node.
   public func expand(
     macros: [String: Macro.Type],
+    conformsTo conformanceMap: [String: InheritedTypeListSyntax],
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:26]: Since `SyntaxProtocol.expand` is a public function, adding a new parameter to it is a source-breaking change. But I think we can safely default it to an empty dictionary for API compatibility.

File: Tests/SwiftSyntaxMacroExpansionTest/ExtensionMacroTests.swift (hunk 2 above)
Comment (ahoppen) [reply Tests/SwiftSyntaxMacroExpansionTest/ExtensionMacroTests.swift:188]: Yes, it probably should be. But that’s unrelated to this PR. Could you file an issue for it @mackoj?

**Review by ahoppen — COMMENTED** [review]
Thank you for tackling this issue @soumyamahunt!

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift (hunk 3 above)
Comment (Matejkob) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: The concept of a `[String: MacroSpec]` dictionary is neat, and I think we can build on that to create an even more robust and clear model.

How about structuring `MacroSpec` to encapsulate parameters specific to each macro's role? We could use an enum with associated values for this purpose, which would provide us with both flexibility and clarity:

```swift
enum MacroRoleContext {
  case expression
  case declaration
  case accessor
  case memberAttribute
  case member
  case peer
  case conformance
  case codeItem
  case `extension`(conformances: [TypeSyntax])
}

struct MacroSpec {
  let type: MacroType
  let macroContext: MacroRoleContext?
}
```

With this design, `MacroSpec` could serve as a clear and intuitive representation of our macro configurations. It inherently guides the developer to provide only the relevant context for each macro role, which enhances code readability and makes future expansions or modifications to `MacroSpec` more manageable.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift (hunk 4 above)
Comment (Matejkob) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:26]: If we would go with `MacroSpec` in the `assertMacroExpansion` function, shouldn't we also at it here?

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift (hunk 3 above)
Comment (ahoppen) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: This does sound very compelling but every change to add new members to one of the macro roles would be API-breaking. For example, recently the `member` macro role gained `conformances` as well (https://github.com/apple/swift-syntax/pull/2004) and changing `case member` to `case member(conformances: [TypeSyntax])` would be API breaking since clients can no longer construct it as `["MyMemberMacro": .member]".

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift (hunk 4 above)
Comment (ahoppen) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:26]: Yes, this function probably changes shape completely with the introduction of `MacroSpec`.

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift (hunk 3 above)
Comment (Matejkob) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: In theory, we could manage that using static variables and default values for associated types, like this:

```swift
enum MacroRoleContext {
  case expression
  // ...
  case member(conformances: [String] = [])
  // ...
  case `extension`(conformances: [String])

  static var defaultMember: Self {
    return .member()
  }
}
```

By doing so, we could also gain a tool to inform users about API changes, by deprecation warnings on those static variables, that they can update their tests with the new functionalities.

Comment (Matejkob) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: btw for the first time we been considering using such a context here https://github.com/apple/swift-syntax/pull/1859#discussion_r1245612254

Comment (ahoppen) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: Unfortunately that’s not possible AFAICT

```swift
enum X {
  case foo(String)

  static var foo: X = .foo("a")
}

let a = X.foo // error: Ambiguous use of 'foo'
```

Comment (Matejkob) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: lol. I'm confused right now. Why this: `let a: X = .foo` works and this: `let a = X.foo` doesn't? 🤯

Comment (Matejkob) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: It doesn't look like a feature... it looks like a bug to me 😵‍💫

Comment (ahoppen) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: Might be worth filing an issue in github.com/apple/swift about

Comment (Matejkob) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:267]: Yeah, I guess so. I've add it [here](https://github.com/apple/swift/issues/69772).

Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift]: > I’m not a fan of adding another parameter to `assertMacroExpansion`. What I would prefer is that the `macros` parameter becomes `[String: MacroSpec]` with
> 
> ```swift
> struct MacroSpec {
>   let type: MacroType
>   let conformances: [TypeSyntax]
> }
> ```
> 
> The benefit of that is that we could expand `MacroSpec` in the future without the need to have more parameters to `assertMacroExpansion`.
> 
> We still need to keep the current function that takes `macros: [String: Macro.Type]` around for API-compatibility.

@ahoppen made this change

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift (hunk 4 above)
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift]: @ahoppen added `MacroSpec` here as well, while keeping the existing definition for compatibility.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 5]
```diff
@@ -355,11 +368,14 @@ private func expandExtensionMacro(
...
   /// Indicates that a macro with the given name has already been defined.
   case alreadyDefined(new: Macro.Type, existing: Macro.Type)
+  /// Indicates that protocol conformances for a macro with the given name has already been defined.
+  case alreadyConforming(new: InheritedTypeListSyntax, existing: InheritedTypeListSyntax)
 }
 
 /// A system of known macros that can be expanded syntactically
 struct MacroSystem {
   var macros: [String: Macro.Type] = [:]
+  var conformanceMap: [String: InheritedTypeListSyntax] = [:]
```
[the remark this answers is not in the document]
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift]: @ahoppen made this change

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 6]
```diff
@@ -355,11 +368,14 @@ private func expandExtensionMacro(
 enum MacroSystemError: Error {
   /// Indicates that a macro with the given name has already been defined.
   case alreadyDefined(new: Macro.Type, existing: Macro.Type)
+  /// Indicates that protocol conformances for a macro with the given name has already been defined.
+  case alreadyConforming(new: InheritedTypeListSyntax, existing: InheritedTypeListSyntax)
```
[the remark this answers is not in the document]
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift]: @ahoppen yes removed this

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 7]
```diff
@@ -316,6 +328,7 @@ private func expandExtensionMacro(
   definition: ExtensionMacro.Type,
   attributeNode: AttributeSyntax,
   attachedTo: DeclSyntax,
+  conformanceList: InheritedTypeListSyntax?,
```
[the remark this answers is not in the document]
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift]: @ahoppen updated

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 8]
```diff
@@ -25,11 +25,23 @@ extension SyntaxProtocol {
...
+    indentationWidth: Trivia? = nil
   ) -> Syntax {
     // Build the macro system.
     var system = MacroSystem()
-    for (macroName, macroType) in macros {
-      try! system.add(macroType, name: macroName)
+    for (macroName, macroSpec) in macroSpecs {
+      try! system.add(macroSpec.type, name: macroName)
+      let conformedTypes = InheritedTypeListSyntax(macroSpec.conformances.map { InheritedTypeSyntax(type: $0) })
+      try! system.add(conformedTypes, name: macroName)
```
[the remark this answers is not in the document]
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift]: @ahoppen updated method signature to have one `add` call

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 9]
```diff
@@ -25,11 +25,23 @@ extension SyntaxProtocol {
     macros: [String: Macro.Type],
```
[the remark this answers is not in the document]
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:27]: @ahoppen added this

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 10]
```diff
@@ -25,11 +25,23 @@ extension SyntaxProtocol {
...
     in context: some MacroExpansionContext,
     indentationWidth: Trivia? = nil
+  ) -> Syntax {
+    let specs = Dictionary(uniqueKeysWithValues: macros.map { ($0.key, MacroSpec(type: $0.value)) })
```
[the remark this answers is not in the document]
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift]: @ahoppen updated

File: Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift [hunk 11]
```diff
@@ -0,0 +1,21 @@
+import SwiftSyntax
```
[the remark this answers is not in the document]
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift:13]: @ahoppen added

File: Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift [hunk 12]
```diff
@@ -0,0 +1,42 @@
...
+//
+// See https://swift.org/LICENSE.txt for license information
+// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
+//
+//===----------------------------------------------------------------------===//
+
+import SwiftSyntax
+import SwiftSyntaxMacros
+
+/// The specification for a macro.
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift:16]:
```suggestion
/// The information of a macro declaration, to be used with `assertMacroExpansion`.
///
/// In addition to specifying the macro’s type, this allows the specification of conformances that will be passed to the macro’s `expansion` function.
```

File: Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+public struct MacroSpec {
+  /// The type of macro.
+  let type: Macro.Type
+  /// The list of types macro needs to add conformances.
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift:20]:
```suggestion
  /// The list of types for which the macro needs to add conformances.
```

File: Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift [hunk 14]
```diff
@@ -0,0 +1,42 @@
...
+  let conformances: [TypeSyntax]
+
+  /// The type list macro needs to add conformances.
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift:23]:
```suggestion
  /// An `InheritedTypeListSytnax` containing all the types for which the macro needs to add conformances.
```

File: Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift [hunk 15]
```diff
@@ -0,0 +1,42 @@
...
+      }
+    }
+  }
+
+  /// Creates a new specification from provided macro type
+  /// and optional list of generated conformances.
+  ///
+  /// - Parameters:
+  ///   - type: The type of macro.
+  ///   - conformances: The list of types macro needs to add conformances.
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift:37]:
```suggestion
  ///   - conformances: The list of types that will be passed to the macro’s `expansion` function.
```

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 16]
```diff
@@ -866,40 +880,40 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
 // MARK:  Attached macro expansions.
 
 extension MacroApplication {
-  /// Get pairs of a macro attribute and the macro definition attached to `decl`.
+  /// Get macro attribute, the macro specification attached to `decl`.
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:883]:
```suggestion
  /// Get pairs of a macro attribute and the macro specification attached to `decl`.
```

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 17]
```diff
@@ -866,40 +880,40 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
...
 
-      return (attribute, macro)
+      return (attribute, macroSpec)
     }
   }
 
-  /// Get pairs of a macro attribute and the macro definition attached to `decl`
-  /// matching `ofType` macro type.
+  /// Get macro attribute, the macro definition and conformance
+  /// protocols list attached to `decl` matching `ofType` macro type.
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:906]:
```suggestion
  /// Get a list of the macro attribute, the macro definition and the conformance
  /// protocols list attached to `decl` matching `ofType` macro type.
```

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 18]
```diff
@@ -294,6 +294,54 @@ func assertDiagnostic(
 ///   - macros: The macros that should be expanded, provided as a dictionary
 ///     mapping macro names (e.g., `"stringify"`) to implementation types
 ///     (e.g., `StringifyMacro.self`).
+///   - conformanceMap: The protocols that macro should conform to, provided as
+///     a dictionary mapping macro names (e.g., `"AddCodable"`) to protocols names
+///     (e.g., `"Decodable"`, `"Encodable"` etc.).
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:299]: I think this is out-of-date

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 19]
```diff
@@ -294,6 +294,54 @@ func assertDiagnostic(
...
+///
+/// - Parameters:
+///   - originalSource: The original source code, which is expected to contain
+///     macros in various places (e.g., `#stringify(x + y)`).
+///   - expectedExpandedSource: The source code that we expect to see after
+///     performing macro expansion on the original source.
+///   - diagnostics: The diagnostics when expanding any macro
+///   - macroSpecs: The macros that should be expanded, provided as a dictionary
+///     mapping macro names (e.g., `"stringify"`) to specification
+///     (e.g., `StringifyMacro.self`).
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:344]:
```
///     (e.g., `StringifyMacro.self`).
```

This example is no longer correct because the function takes `MacroSpec` now, not macro types.

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 20]
```diff
@@ -294,6 +294,54 @@ func assertDiagnostic(
...
+  macros: [String: Macro.Type],
+  applyFixIts: [String]? = nil,
+  fixedSource expectedFixedSource: String? = nil,
+  testModuleName: String = "TestModule",
+  testFileName: String = "test.swift",
+  indentationWidth: Trivia = .spaces(4),
+  file: StaticString = #file,
+  line: UInt = #line
+) {
+  let specs = Dictionary(uniqueKeysWithValues: macros.map { ($0.key, MacroSpec(type: $0.value)) })
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:319]: I think you can also use `mapValues` here.

**Review by ahoppen — COMMENTED** [review]
Thank you 🙏🏽 Looks very good. I just have a few comments on the documentation.

Also: Could you add an entry fro this in the 511.md release notes?

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift (hunk 20 above)
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift]: Updated with this change

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift (hunk 19 above)
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift]: @ahoppen updated example

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift (hunk 18 above)
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift]: @ahoppen removed this

**Review by ahoppen — APPROVED** [review]
Thanks!

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
This solution looks really nice, thank you!

File: Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift:1]: You need to add this file to [CMakeLists.txt](https://github.com/apple/swift-syntax/blob/main/Sources/SwiftSyntaxMacroExpansion/CMakeLists.txt) as well so we can build swift-syntax using CMake for the compiler.

**Comment by ahoppen** [comment]
Looks like this has a few merge conflicts now. Could you resolve them @soumyamahunt?

File: Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift
Comment (soumyamahunt) [reply Sources/SwiftSyntaxMacroExpansion/MacroSpec.swift:1]: Added

**Comment by soumyamahunt** [comment]
@ahoppen resolved conflicts

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by Matejkob — COMMENTED** [review]
How about squashing commits?

**Comment by ahoppen** [comment]
Looks like the documentation contains a few invalid references now. Could you resolve them by making sure that `./swift-syntax-dev-utils verify-documentation` passes?

**Comment by soumyamahunt** [comment]
@ahoppen documentation links are fixed and commits squashed

**Comment by ahoppen** [comment]
Thank you. There was a merge conflict in the release notes now. I took the liberty to fix it and force-push to your branch.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows
