### PR TITLE
[Macros] Implement expansion of conformance macros

### LINKED ISSUE #1742: SyntaxProtocol.expand() does not expand conformance macros
### Description

Conformance macros used in the input source are discarded without expansion. A basic example:

```swift
struct Conformance: ConformanceMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingConformancesOf declaration: some DeclGroupSyntax,
        in context: some MacroExpansionContext
    ) throws -> [(TypeSyntax, GenericWhereClauseSyntax?)] {
        fatalError()
    }
}
assertMacroExpansion("@Foo class Bar {}", expandedSource: "class Bar {\n}",
                     macros: ["Foo": Conformance.self])
```

This test passes despite the implementation being `fatalError()` due to `expansion(of:performanceConformanceOf:in:)` never being called. There appears to be two parallel implementations of macro expansion with ConformanceMacro only being supported in expandAttachedMacro(), which is not called by SyntaxProtocol.expand().

There may be other macro types not implemented as well; I did not try them all.

### Steps to Reproduce

_No response_

### PR DESCRIPTION
**Pull request by DougGregor**
Somehow, we forgot to implement this here, even though the compiler has supported it for a long time.

Fixes #1742 / rdar://110418242.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

File: Sources/SwiftSyntaxMacros/MacroSystem.swift [hunk 1]
```diff
@@ -394,6 +403,43 @@ extension MacroApplication {
     return peers
   }
 
+  // If any of the custom attributes associated with the given declaration
+  // refer to conformance macros, expand them and return the resulting
+  // set of extension declarations.
+  private func expandConformances(of decl: DeclGroupSyntax) -> [DeclSyntax] {
+    let identifier: String
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacros/MacroSystem.swift:410]: Why not make `identifier: Syntax` and then you don’t need to convert to strings or  use the `raw` interpolation below. Also `identifier` isn’t correct because `ext.extendedType` is not an identifier.

File: Sources/SwiftSyntaxMacros/MacroSystem.swift [hunk 2]
```diff
@@ -394,6 +403,43 @@ extension MacroApplication {
...
+    for (attribute, conformanceMacro) in macroAttributes {
+      do {
+        let newConformances = try conformanceMacro.expansion(of: attribute, providingConformancesOf: decl, in: context)
+
+        for (type, whereClause) in newConformances {
+          var ext: DeclSyntax = """
+            extension \(raw: identifier): \(type) { }
+            """
+          if let whereClause {
+            ext = DeclSyntax((ext.as(ExtensionDeclSyntax.self))!.with(\.genericWhereClause, whereClause))
```
[the remark this answers is not in the document]
Comment (DougGregor) [reply Sources/SwiftSyntaxMacros/MacroSystem.swift]: Thank you, I've pulled this in!

File: Sources/SwiftSyntaxMacros/MacroSystem.swift (hunk 1 above)
Comment (DougGregor) [reply Sources/SwiftSyntaxMacros/MacroSystem.swift]: Great point, I've updated this code.

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Windows
