### PR TITLE
Fix missing newline in member macro

### LINKED ISSUE #2307: MacroSystem should add newline at the end of added members for an empty type
### Description

Given a macro `AddMembers` that does as its name suggests, MacroSystem will currently expand the following:
```
@AddMembers struct Foo {}
```

To:
```
struct Foo {
  func addedMember() {
    ...
  }}
```

Note the lack of a newline after the added member. This usually makes sense as there would already be one, but when there isn't, we should add it.

rdar://116773975

### Steps to Reproduce

_No response_

### PR DESCRIPTION
**Pull request by kimdv**
Fixes #2307

### CODE REVIEW

File: Sources/SwiftParser/ParseSourceFile.swift [hunk 1]
```diff
@@ -152,8 +152,25 @@ extension Parser {
     }
 
     let remainingTokens = self.consumeRemainingTokens()
+
+    func parseEndOfFileIfPresent(raw: RawSyntax) -> R? {
```
Comment (ahoppen) [inline Sources/SwiftParser/ParseSourceFile.swift:156]: I would make this a `private` function in the extension. That just seems cleaner to me. Nested functions always give me the feeling that they might be capturing outside state and I don’t look for them.

Also, I would name it something that explicitly mentions the leading trivia and add a doc comment.

File: Sources/SwiftParser/ParseSourceFile.swift [hunk 2]
```diff
@@ -152,8 +152,25 @@ extension Parser {
...
+      if let endOfFileToken = self.consume(if: .endOfFile),
+        !endOfFileToken.leadingTriviaPieces.isEmpty,
+        let raw = raw.withTrailingTrivia(
+          Trivia(
+            rawPieces: endOfFileToken.leadingTriviaPieces
+          ),
```
Comment (ahoppen) [inline Sources/SwiftParser/ParseSourceFile.swift:162]: You are dropping the existing trailing trivia here. I expect this test to fail

```swift
  func testDeclarationEndingWithGarbageAndNewline() {
    let input = "var x = 0 \n"
    let decl = DeclSyntax(stringLiteral: input)
    XCTAssertEqual(decl.description, input)
  }
```

File: Sources/SwiftParser/ParseSourceFile.swift [hunk 3]
```diff
@@ -152,8 +152,25 @@ extension Parser {
...
+          arena: self.arena
+        )
+      {
+        return R.init(raw)!
+      } else {
+        return nil
```
Comment (ahoppen) [inline Sources/SwiftParser/ParseSourceFile.swift:168]: What about just returning `raw` here? That way you don’t need to do `??` on every call

File: Sources/SwiftParser/ParseSourceFile.swift [hunk 4]
```diff
@@ -166,6 +183,14 @@ extension Parser {
     let unexpected = RawUnexpectedNodesSyntax(elements: existingUnexpected + remainingTokens, arena: self.arena)
 
     let withUnexpected = layout.replacingChild(at: layout.children.count - 1, with: unexpected.raw, arena: self.arena)
-    return R.init(withUnexpected)!
+
+    return parseEndOfFileIfPresent(raw: withUnexpected) ?? R.init(withUnexpected)!
+  }
+}
+
+extension Trivia {
```
Comment (ahoppen) [inline Sources/SwiftParser/ParseSourceFile.swift:191]: I would make this `private`. Makes it more local.

File: Sources/SwiftSyntax/Raw/RawSyntax.swift [hunk 5]
```diff
@@ -328,7 +328,8 @@ extension RawSyntax {
   /// - Parameters:
   ///   - trailingTrivia: The trivia to attach.
   ///   - arena: SyntaxArena to the result node data resides.
-  func withTrailingTrivia(_ trailingTrivia: Trivia, arena: SyntaxArena) -> RawSyntax? {
+  @_spi(RawSyntax)
+  public func withTrailingTrivia(_ trailingTrivia: Trivia, arena: SyntaxArena) -> RawSyntax? {
```
Comment (ahoppen) [inline Sources/SwiftSyntax/Raw/RawSyntax.swift:332]: If you make this SPI, could you also make `withLeadingTrivia` SPI for symmetry?

File: Sources/SwiftParser/ParseSourceFile.swift [hunk 6]
```diff
@@ -166,6 +167,33 @@ extension Parser {
...
 
     let withUnexpected = layout.replacingChild(at: layout.children.count - 1, with: unexpected.raw, arena: self.arena)
-    return R.init(withUnexpected)!
+
+    return R.init(transferTrailingTrivaFromEndOfFileIfPresent(raw: withUnexpected))!
+  }
+
+  /// Parses the end-of-file token and appends its leading trivia to the provided `RawSyntax`.
+  /// - Parameter raw: The raw syntax node to which the leading trivia of the end-of-file token will be appended.
+  /// - Returns: An instance of the generic type `R` if the end-of-file token is present, or `nil` otherwise.
```
Comment (bnbarham) [inline Sources/SwiftParser/ParseSourceFile.swift:176]: Comment seems out of date

File: Sources/SwiftParser/ParseSourceFile.swift [hunk 7]
```diff
@@ -166,6 +167,33 @@ extension Parser {
...
+        Trivia(
+          rawPieces: (raw.trailingTriviaPieces ?? []) + endOfFileToken.leadingTriviaPieces
+        ),
+        arena: self.arena
+      )
+    {
+      return raw
+    } else {
+      return raw
+    }
```
Comment (bnbarham) [inline Sources/SwiftParser/ParseSourceFile.swift:190]: Personally I'd `guard let ... else { return raw }` to avoid the nesting

File: Tests/SwiftSyntaxMacroExpansionTest/MemberMacroTests.swift [hunk 8]
```diff
@@ -299,4 +299,62 @@ final class MemberMacroTests: XCTestCase {
...
+    assertMacroExpansion(
+      """
+      @Test
+      struct Foo {}
+      """,
+      expandedSource: """
+        struct Foo {
+
+          var x = 0}
+        """,
```
Comment (bnbarham) [inline Tests/SwiftSyntaxMacroExpansionTest/MemberMacroTests.swift:324]: My expectation is that this should be:
```
struct Foo {
  var x = 0
}
```

Same in the next test as well. Am I missing something?

Comment (kimdv) [reply Tests/SwiftSyntaxMacroExpansionTest/MemberMacroTests.swift]: Got it now.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 9]
```diff
@@ -758,37 +758,42 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
...
         // Recurse on the child node.
-        newItems.append(visit(node))
+
+        // Ensure there is only one newline if there is no member.
+        if newItems.isEmpty && node.members.isEmpty {
+          let singleNewlineTrivia = memberBlockItem.leadingTrivia.trimmingPrefix(while: { $0.isNewline })
+          newItems.append(visit(memberBlockItem.with(\.leadingTrivia, .newline + singleNewlineTrivia)))
+        } else {
+          newItems.append(visit(memberBlockItem))
+        }
```
Comment (kimdv) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:786]: I'm not sure if this is the right approach. 

In MacroSystem.swift:212 we add `\n\n`. And here I want to override it

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 10]
```diff
@@ -821,7 +826,28 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
...
+    /// Returns an leading trivia for the member blocks closing brace.
+    /// It will add a leading newline, if there is none.
+    var leadingTriviaForClosingBrace: Trivia {
+      guard !node.members.isEmpty || !newItems.isEmpty else {
+        return node.rightBrace.leadingTrivia
+      }
+
+      guard !node.rightBrace.leadingTrivia.contains(where: { $0.isNewline }) else {
+        return node.rightBrace.leadingTrivia
+      }
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:838]: I think these would read easier as `if` statements because we could avoid the negations then.

File: Tests/SwiftSyntaxMacroExpansionTest/ExtensionMacroTests.swift [hunk 11]
```diff
@@ -85,26 +85,26 @@ final class ExtensionMacroTests: XCTestCase {
...
+    //          struct MyType {
+    //          }
+    //        }
+    //
+    //        extension MyType: Sendable {
+    //        }
+    //        """,
+    //      macros: ["AddSendableExtension": SendableExtensionMacro.self],
+    //      indentationWidth: indentationWidth
+    //    )
```
Comment (ahoppen) [inline Tests/SwiftSyntaxMacroExpansionTest/ExtensionMacroTests.swift:107]: Did you uncomment this test intentionally?

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift (hunk 9 above)
Comment (kimdv) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:786]: @bnbarham do you also think it's fine? 
You mentioned here that you would expect without: https://github.com/apple/swift-syntax/pull/2320#discussion_r1406497566

Comment (bnbarham) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:786]: I don't really mind. I think it would be nice to remove and this isn't that much of a hack, but on the other hand the two `\n\n` is what the compiler sees, so you could argue it makes sense to keep them. As long as we add a newline before the `}`, I'm happy :)

File: Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift [hunk 12]
```diff
@@ -151,7 +151,7 @@ final class PeerMacroTests: XCTestCase {
           Task {
             completionHandler(await f(a: a, for: b, value))
           }
-        }
+          }
```
[the remark this answers is not in the document]
Comment (kimdv) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift:154]: Okay, I removed trailing and leading newline at it got fixed.. Dunno why tough? 
Should I dig more into it.

[the remark this answers is not in the document]
Comment (ahoppen) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: Where did you remove the trailing and leading newline?

**Review by ahoppen — APPROVED** [review]

File: Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift (hunk 12 above)
[the remark this answers is not in the document]
Comment (kimdv) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: Inside: Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift

[the remark this answers is not in the document]
Comment (ahoppen) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: I think it would be nice to understand why the behavior changed.

[the remark this answers is not in the document]
Comment (kimdv) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: It happens in the new `transferTrailingTrivaFromEndOfFileIfPresent`
The raw input is `transferTrailingTrivaFromEndOfFileIfPresent` and we return `"\n  Task {\n    completionHandler(await f(a: a, for: b, value))\n  }\n"`

So I think it's because we transfer the leading trivia to the trailing part.
And because it have a newline at the end, we have double newline.

[the remark this answers is not in the document]
Comment (ahoppen) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: You nerd-sniped me into this one: I’m fixing the issue in https://github.com/apple/swift-syntax/pull/2428

[the remark this answers is not in the document]
Comment (ahoppen) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: The changes you made in this PR still make sense to me. So good to go 👍🏽

**Comment by ahoppen** [comment]
FWIW: Working on https://github.com/apple/swift-syntax/pull/2428, I noticed that there’s still a formatting issue in this code, I think.

File: Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift (hunk 12 above)
[the remark this answers is not in the document]
Comment (kimdv) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: > You nerd-sniped me into this one: I’m fixing the issue in https://github.com/apple/swift-syntax/pull/2428

Sorry 🤣

**Comment by kimdv** [comment]
> FWIW: Working on https://github.com/apple/swift-syntax/pull/2428, I noticed that there’s still a formatting issue in this code, I think. I.e. you need to re-run `swift-format`.

Will rebase after #2428 is merged.

File: Tests/SwiftBasicFormatTest/BasicFormatTests.swift [hunk 13]
```diff
@@ -588,6 +588,7 @@ final class BasicFormatTest: XCTestCase {
         func test() {
             Task {
             }
+
```
Comment (kimdv) [inline Tests/SwiftBasicFormatTest/BasicFormatTests.swift:591]: @ahoppen after your PR was merged, it introduced a newline here.

It is happening inside the `transferTrailingTrivaFromEndOfFileIfPresent`, where we add `endOfFileToken.leadingTriviaPieces`

Comment (ahoppen) [reply Tests/SwiftBasicFormatTest/BasicFormatTests.swift:591]: Yes, that’s expected because we no longer discard the `\n\n` after the `Task {\n}`.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 14]
```diff
@@ -825,7 +823,28 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
       }
     }
 
-    return .init(newItems)
+    /// Returns an leading trivia for the member blocks closing brace.
+    /// It will add a leading newline, if there is none.
+    var leadingTriviaForClosingBrace: Trivia {
+      if (node.members.isEmpty || newItems.isEmpty) && newItems.isEmpty {
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:829]: Reading the code for the 4-th time I just realized. Isn’t this logically equivalent to

```suggestion
      if newItems.isEmpty {
```

**Review by ahoppen — APPROVED** [review]

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 15]
```diff
@@ -825,7 +823,29 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
...
+
+      if newItems.last?.trailingTrivia.pieces.last?.isNewline ?? false {
+        return node.rightBrace.leadingTrivia
+      } else {
+        return .newline + node.rightBrace.leadingTrivia
+      }
+    }
+
+    return MemberBlockSyntax(
+      leftBrace: node.leftBrace,
```
Comment (kimdv) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:845]: @ahoppen added `leftBrace: node.leftBrace,` since your review. 

If not, it will fail `testAssertMacroExpansionIgnoresHighlightMatchingIfNil` where `"struct S { }"` -> `"struct S {}"`

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test windows
