### PR TITLE
Fix it to emit a single diagnostic when both open and close quote are missing

### LINKED ISSUE #1691: Parser should emit a single diagnostic if both open and close quote are missing from string literal
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
@_expose(Cxx, baz) func foo() {}
```

### Description

From https://github.com/apple/swift-syntax/pull/1688/files#r1201105564

In the above example the parser produces two diagnostics: One for the missing opening `"` before `baz` and one for the missing closing `"` after `baz`. It should emit a single diagnostic instead that offers to add both.

### PR DESCRIPTION
**Pull request by TTOzzi**
Resolve #1691 

When a string segment is located between missing quotes on both sides, looking ahead is interrupted, and each quote is diagnosed separately. 
I have modified the logic to continue looking ahead even if a standalone string segment is encountered during the search.
Furthermore, I added a condition to the `parentContextClause` in order to modify the diagnostic, but I am uncertain if it is the appropriate approach.
If there is a better solution available, please let me know. Thank you.

### CODE REVIEW

File: Sources/SwiftParserDiagnostics/MissingNodesError.swift [hunk 1]
```diff
@@ -364,7 +370,10 @@ extension ParseDiagnosticsGenerator {
           missingNodes += [sibling]
         } else if sibling.isMissingAllTokens && sibling.hasTokens {
           missingNodes += [sibling]
-        } else if sibling.kind.isSyntaxCollection && sibling.children(viewMode: .sourceAccurate).count == 0 {
+        } else if sibling.kind.isSyntaxCollection
+          && (sibling.children(viewMode: .sourceAccurate).count == 0
+            || sibling.children(viewMode: .sourceAccurate).only?.kind == .stringSegment)
```
Comment (TTOzzi) [inline Sources/SwiftParserDiagnostics/MissingNodesError.swift:375]: (If my approach is correct...) How about separating this part as a property named `isSingleToken`(or a more appropriate name) and accessing it as `sibling.isSingleToken`?

**Review by ahoppen — COMMENTED** [review]
The way I would approach this is to add 

```swift
public override func visit(_ node: StringLiteralExprSyntax) -> SyntaxVisitorContinueKind {
```

to `ParseDiagnosticsGenerator`. If both `node.openQuote` and `node.closeQuote` are missing, you can generate a custom error message.

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift [hunk 2]
```diff
@@ -386,6 +386,14 @@ public struct MissingAttributeArgument: ParserError {
   }
 }
 
+public struct MissingBothStringQuotesOfStringSegments: ParserError {
+  public let stringSegments: StringLiteralSegmentsSyntax
+
+  public var message: String {
+    return "expected \(nodesDescription([stringSegments], format: false)) to be surrounded by '\"'"
```
Comment (ahoppen) [inline Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:393]: If you just want to print the source test of `stringSegments` verbatim, I would use `. shortSingleLineContentDescription ` instead. The core functionality of `nodesDescription` is to paraphrase entire nodes by their node name but I don’t think that’s something we want here.

```suggestion
    return "expected '\(stringSegments.shortSingleLineContentDescription)' to be surrounded by '\"'"
```

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift [hunk 3]
```diff
@@ -1257,7 +1257,29 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
           node.closeQuote.id,
         ].compactMap { $0 }
       )
+    } else if (node.openQuote.tokenKind == .stringQuote && node.openQuote.presence == .missing),
+      (node.closeQuote.tokenKind == .stringQuote && node.closeQuote.presence == .missing),
+      !node.segments.isMissingAllTokens
```
Comment (ahoppen) [inline Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1262]: There’s no need to use `&&` or parentheses here. `,` in an `if` statement is a conjunction already. 

---

Also, I don’t think it’s necessary to check for the token kind of `openQuote` and `closeQuote`. The parser doesn’t generate any trees that hit this at the moment but in theory the diagnostic should also work for multi-line string literals where the `tokenKind` is `multilineStringQuote`. You’d just need to pass the kind of the quote to the error message.

File: Tests/SwiftParserTest/AttributeTests.swift [hunk 4]
```diff
@@ -543,20 +538,15 @@ final class AttributeTests: XCTestCase {
...
-          message: #"expected '"' in string literal"#,
-          fixIts: [#"insert '"'"#]
-        ),
-        DiagnosticSpec(
-          locationMarker: "2️⃣",
-          message: #"expected '"' to end string literal"#,
-          fixIts: [#"insert '"'"#]
-        ),
+          message: #"expected 'abc' to be surrounded by '"'"#,
+          fixIts: [#"insert '""'"#]
```
Comment (ahoppen) [inline Tests/SwiftParserTest/AttributeTests.swift:548]: I suspect that this will change to `insert '"' and '"'` after https://github.com/apple/swift-syntax/pull/1651 is merged.

**Review by ahoppen — COMMENTED** [review]
Thank you. Looks very good. I only have a few minor comments to make it slightly more general

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift (hunk 2 above)
Comment (TTOzzi) [reply Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:393]: Oh, I agree. Using shortSingleLineContentDescription instead of nodesDescription seems to be in line with the intention we want.

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift (hunk 3 above)
Comment (TTOzzi) [reply Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1262]: I just wanted to express the conditions for both the openQuote and closeQuote separately 😁
As there is no particular significance, I will make the change and differentiate them using a comma!

----

Hmm... If we don't check types of quotes here or check if a newline is included in the trivia of the quote token, this test case will fail.

```swift
  func testRawStringErrors6() {
    assertParse(
      ###"""
      let _ = ##"""1️⃣aa
        foobar
        aa2️⃣"""##
      """###,
      diagnostics: [
        DiagnosticSpec(locationMarker: "1️⃣", message: "multi-line string literal content must begin on a new line", fixIts: ["insert newline"]),
        DiagnosticSpec(locationMarker: "2️⃣", message: "multi-line string literal closing delimiter must begin on a new line", fixIts: ["insert newline"]),
      ],
      fixedSource: ###"""
        let _ = ##"""
          aa
          foobar
          aa
          """##
        """###
    )
  }
```

In the given case, both the openQuote and closeQuote tokens are marked as missing, but in reality, the quote exists with the missing only newline.

Are there cases in multiline string expressions where both quotes are missing and we need to emit a diagnostic similar to the one we just added, suggesting insert `"""` to surrounding them?

Or should we generate a single diagnostic here for the missing of a newline, instead of `handleInvalidMultilineStringQuote` called from `handleMissingToken`?

File: Tests/SwiftParserTest/AttributeTests.swift (hunk 4 above)
Comment (TTOzzi) [reply Tests/SwiftParserTest/AttributeTests.swift:548]: Thank you for letting me know! Once the PR is merged, I will rebase to apply the changes 🙂

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift [hunk 5]
```diff
@@ -386,6 +386,14 @@ public struct MissingAttributeArgument: ParserError {
   }
 }
 
+public struct MissingBothStringQuotesOfStringSegments: ParserError {
+  public let stringSegments: StringLiteralSegmentsSyntax
```
Comment (kimdv) [inline Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:390]: The variable name is `stringSegments` but is not an array?
Is it?

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift (hunk 2 above)
Comment (kimdv) [inline Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:393]: Instead of escaping `"` then you could use `#` at the start and end of the string.
I think Rae strings reads a little easier

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift (hunk 3 above)
Comment (ahoppen) [reply Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1262]: Oh, I see. In that case maybe check that `unexpectedBeforeOpenQuote` and `unexpectedBeforeCloseQuote` are `nil` because they will contain the string quotes without a newline in the test case above.

Comment (TTOzzi) [reply Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1262]: Ah, this works as intended and is more general than checking the token kind! Thank you for providing your feedback.

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift (hunk 5 above)
Comment (TTOzzi) [reply Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:390]: This is not an array, but I declared it this way to align the node's property names and meanings passed when generating messages. Examples include `components` in `TrailingVersionAreIgnored` or `unexpectedNodes` in `UnexpectedNodesError`. 
Do you think it would be better to declare it simply as `stringSegment`?

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift (hunk 2 above)
Comment (TTOzzi) [reply Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:393]: Oh, that's great! Using a raw string seems more readable. I will make the change. Thank you 🙂

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift (hunk 5 above)
Comment (kimdv) [reply Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:390]: After diving in the code, it looks like `StringLiteralSegmentsSyntax` also is a `SyntaxCollection`. Just like `TrailingVersionAreIgnored ` and `UnexpectedNodesError `
So you can completely ignore this comment 🫠

**Review by kimdv — APPROVED** [review]

**Review by ahoppen — APPROVED** [review]
Thank you. This looks great now. Can you rebase it now that https://github.com/apple/swift-syntax/pull/1651 is merged? Afterwards, I’ll trigger CI.

File: Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift (hunk 5 above)
Comment (TTOzzi) [reply Sources/SwiftParserDiagnostics/ParserDiagnosticMessages.swift:390]: Ah, it seems that all of these have a common protocol called `SyntaxCollection`! Thank you for your feedback 🙇‍♂️

**Comment by TTOzzi** [comment]
> Thank you. This looks great now. Can you rebase it now that #1651 is merged? Afterwards, I’ll trigger CI.

I'm done! Thank you @ahoppen 🙌

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test windows
