### PR TITLE
Parse `return @unknown default` correctly

### LINKED ISSUE #933: Unexpected MissingExprSyntax when empty return precedes "@unknown default" in switch statement
### Issue Kind

Parse of Valid Source Produced Invalid Syntax Tree

### Source Code

```swift
public func bar_bad(foo: Int) {
  switch foo {
  case 0:
    return
  @unknown default:
    return
  }
}
```

### Description

This produces the following parse tree:

```
SourceFileSyntax children=2
  0: CodeBlockItemListSyntax children=1
    0: CodeBlockItemSyntax children=1
      0: FunctionDeclSyntax children=5
        0: ModifierListSyntax children=1
          0: DeclModifierSyntax children=1
            0: publicKeyword
        1: funcKeyword
        2: identifier("bar_bad")
        3: FunctionSignatureSyntax children=1
          0: ParameterClauseSyntax children=3
            0: leftParen
            1: FunctionParameterListSyntax children=1
              0: FunctionParameterSyntax children=3
                0: identifier("foo")
                1: colon
                2: SimpleTypeIdentifierSyntax children=1
                  0: identifier("Int")
            2: rightParen
        4: CodeBlockSyntax children=3
          0: leftBrace
          1: CodeBlockItemListSyntax children=1
            0: CodeBlockItemSyntax children=1
              0: SwitchStmtSyntax children=5
                0: switchKeyword
                1: IdentifierExprSyntax children=1
                  0: identifier("foo")
                2: leftBrace
                3: SwitchCaseListSyntax children=2
                  0: SwitchCaseSyntax children=2
                    0: SwitchCaseLabelSyntax children=3
                      0: caseKeyword
                      1: CaseItemListSyntax children=1
                        0: CaseItemSyntax children=1
                          0: ExpressionPatternSyntax children=1
                            0: IntegerLiteralExprSyntax children=1
                              0: integerLiteral("0")
                      2: colon
                    1: CodeBlockItemListSyntax children=1
                      0: CodeBlockItemSyntax children=1
                        0: ReturnStmtSyntax children=2
                          0: returnKeyword
                          1: MissingExprSyntax
                  1: SwitchCaseSyntax children=3
                    0: AttributeSyntax children=2
                      0: atSign
                      1: identifier("unknown")
                    1: SwitchDefaultLabelSyntax children=2
                      0: defaultKeyword
                      1: colon
                    2: CodeBlockItemListSyntax children=1
                      0: CodeBlockItemSyntax children=1
                        0: ReturnStmtSyntax children=1
                          0: returnKeyword
                4: rightBrace
          2: rightBrace
  1: eof
```

Notice how the `ReturnStmtSyntax` includes a `MissingExprSyntax` as a child. I think that's incorrect because the "empty return" is valid in this situation. If the return isn't empty, either by adding a semicolon or returning a value, or if the next case isn't `@unknown default` then the parser handles it correctly.

### PR DESCRIPTION
**Pull request by ahoppen**
Fixes #933
Resolves rdar://101060095

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

File: Sources/SwiftParser/Statements.swift [hunk 1]
```diff
@@ -906,7 +916,7 @@ extension Parser {
         .poundIfKeyword, .poundErrorKeyword, .poundWarningKeyword,
         .poundEndifKeyword, .poundElseKeyword, .poundElseifKeyword
       ])
-        && !self.atStartOfStatement() && !self.atStartOfDeclaration() {
+        && !self.atStartOfStatement() && !self.atStartOfDeclaration() && !self.withLookahead({ $0.atStartOfSwitchCaseItem() }) {
```
Comment (CodaFi) [inline Sources/SwiftParser/Statements.swift:919]: We should fix this in `atStartOfStatement`. This is ultimately a regression there because we dropped the clause that checks for `(@attr)* <identifier>`

Comment (ahoppen) [reply Sources/SwiftParser/Statements.swift:919]: Do you think that case labels should return `true` for `atStartOfStatement`? Because in my opinion these are not statements. If anything, I’d say that case labels are declarations, but even that I don’t think they are.

**Comment by ahoppen** [comment]
@swift-ci Please test

File: Sources/SwiftParser/Statements.swift (hunk 1 above)
Comment (CodaFi) [reply Sources/SwiftParser/Statements.swift:919]: I would say yeah they're not real statements, but if we intend to match the behavior of the legacy parser, then we have to consider them a part of that predicate so the rest of the parser picks this up too.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by CodaFi — APPROVED** [review]
