### PR TITLE
Remove spacing between `Any` and `.`

### LINKED ISSUE #1815: "Any.Type" in header always outputs as "Any .Type" with an extra space
### Description

246605376-4701d2cb-b77b-4c23-a427-aa7612a528f1
---
"Any.Type" in header always outputs as "Any .Type" with an extra space.

### Steps to Reproduce

_No response_

### PR DESCRIPTION
**Pull request by kimdv**
Resolves #1815 

Companion PR https://github.com/apple/swift/pull/66799

### CODE REVIEW

**Comment by kimdv** [comment]
@ahoppen should it be cherry picked to `release/5.9`

File: Tests/SwiftSyntaxBuilderTest/VariableTests.swift [hunk 1]
```diff
@@ -371,4 +371,20 @@ final class VariableTests: XCTestCase {
       assertBuildResult(builder, expected, line: line)
     }
   }
+
+  // https://github.com/apple/swift-syntax/issues/1815
+  func testSpacingInDictionaryType() throws {
+    let header = PartialSyntaxNodeString(stringLiteral: "static var mirror: Dictionary<String, Any.Type>")
+    let buildable = try VariableDeclSyntax(header) {
+
+    }
```
Comment (ahoppen) [inline Tests/SwiftSyntaxBuilderTest/VariableTests.swift:380]: Do you need to explicitly construct a `PartialSyntaxNodeString` here? Wouldn’t any of the following do the job equally well here? Also: Shouldn’t this test case be in *SwiftBasicFormatTest* instead of *SwiftSyntaxBuilderTest*?

Wouldn’t 

```swift
let buildable = """
static var mirror: Dictionary<String, Any.Type> {}
"""
```

or 

```swift
let buildable = try VariableDeclSyntax("static var mirror: Dictionary<String, Any.Type>") {}
```

Comment (kimdv) [reply Tests/SwiftSyntaxBuilderTest/VariableTests.swift:380]: It was to come as close ro the GitHub issue as possible. 
I can change to the last example if you want.

Comment (ahoppen) [reply Tests/SwiftSyntaxBuilderTest/VariableTests.swift:380]: Ah, I see. In that case either really makes sense. Feel free to keep it.

Comment (kimdv) [reply Tests/SwiftSyntaxBuilderTest/VariableTests.swift]: Changed to the last example

**Comment by kimdv** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/66799

@swift-ci please test
