### PR TITLE
Fold operators using the standard operator table in `MacroSystem`

### LINKED ISSUE #2128: No way to describe operator precedence to `assertMacroExpansion`
### Description

It doesn't seem possible to write tests for macros that visit `InfixOperatorExprSyntax`. This includes the "add blocker" example from swift-macro-examples.

### Steps to Reproduce

1. Try to write a macro test for: https://github.com/DougGregor/swift-macro-examples/blob/66ded9b2774c06c5a51254b0640a456ef1055a68/MacroExamplesPlugin/AddBlocker.swift
2. The `AddVisitor` never visits the node because the node doesn't exist in the test run.

### PR DESCRIPTION
**Pull request by ahoppen**
The compiler folds operators in attributes and freestanding macro nodes but `MacroSystem` wasn’t doing that. But it should to match the compiler behavior.

rdar://114786803
Fixes #2128

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 1]
```diff
@@ -979,4 +980,47 @@ private extension SyntaxProtocol {
...
+
+private extension FreestandingMacroExpansionSyntax {
+  /// Same as `SyntaxProtocol.detach(in:foldingWith:)` but returns a node of type
+  /// `Self` since we know that operator folding doesn't change the type of any
+  /// `FreestandingMacroExpansionSyntax`.
+  func detach(
+    in context: MacroExpansionContext,
+    foldingWith operatorTable: OperatorTable?
+  ) -> Self {
+    return (detach(in: context, foldingWith: operatorTable) as Syntax).cast(Self.self)
```
Comment (bnbarham) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:1012]:
```suggestion
    return (detach(in: context, foldingWith: operatorTable) as Syntax).cast(Self.self)
```

What's the `as` needed for here? Doesn't this already return a `Syntax`?

**Review by bnbarham — APPROVED** [review]

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift (hunk 1 above)
Comment (ahoppen) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:1012]: It’s to disambiguate the version of `detach` that is being called. Without `as Syntax` we would have an infinite recursion here.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows
