### PR TITLE
Generate missing string closer quote and delimiter

### LINKED ISSUE #668: SwiftParser crash when parsing `#"""`
### Issue Kind

Parser Crash

### Source Code

```
#"""
```

### Description

```
[omochi@omochi-iMacPro swift-syntax (main %=)]$ cat temp/crash0.swift 
#"""[omochi@omochi-iMacPro swift-syntax (main %=)]$ .build/debug/swift-parser-test verify-round-trip temp/crash0.swift 
Swift/Collection.swift:711: Fatal error: Out of bounds: index >= endIndex
Illegal instruction: 4
```

I try to fix it

### PR DESCRIPTION
**Pull request by omochi**
This PR fix #668 #669.

If closer quote and delimiter is missing but opener ones are present,
generate missing token to fix round trip bug and emit missing diagnostics.

### CODE REVIEW

File: Sources/SwiftParser/Expressions.swift [hunk 1]
```diff
@@ -907,7 +907,9 @@ extension Parser {
       at: openDelimiter != nil ? .leadingRaw : .leading,
       text: text
     ) ?? RawTokenSyntax(missing: .stringQuote, arena: arena)
-    text = text.dropFirst(openQuote.tokenText.count)
+    if !openQuote.isMissing {
```
Comment (omochi) [inline Sources/SwiftParser/Expressions.swift:910]: I fixed logic here.

If opener quote missing token is generated, don't drop text.

File: Sources/SwiftParser/Expressions.swift [hunk 2]
```diff
@@ -917,16 +919,37 @@ extension Parser {
     /// Parse close quote.
     let closeQuote = self.parseStringLiteralQuote(
       at: openDelimiter != nil ? .trailingRaw : .trailing,
-      text: text[closeStart...]
+      text: text
```
Comment (omochi) [inline Sources/SwiftParser/Expressions.swift:922]: subscript is unnecessary here

File: Sources/SwiftParser/Expressions.swift [hunk 3]
```diff
@@ -1060,7 +1083,10 @@ extension Parser {
       // position == .leadingRaw implies that we saw a `#` before the quote.
       // A multiline string literal must always start its contents on a new line.
       // Thus we are parsing somethign like #"""#, which is not a multiline string literal but a raw literal containing a single quote.
-      if position == .leadingRaw && text[index] == UInt8(ascii: "#") {
+      if position == .leadingRaw,
+         index < text.endIndex,
+         text[index] == UInt8(ascii: "#")
```
Comment (omochi) [inline Sources/SwiftParser/Expressions.swift:1088]: This subscript access may access out of bounds.
I added checking of range.

File: Tests/SwiftParserTest/Expressions.swift [hunk 4]
```diff
@@ -310,6 +310,36 @@ final class ExpressionTests: XCTestCase {
        """"""#^DIAG^#
        """##
      )
+
+    AssertParse(
+      ##"""
+      #"#^DQ^##^DD^#
```
Comment (omochi) [inline Tests/SwiftParserTest/Expressions.swift:316]: Though I didn't report this input, it was also failed before.

File: Sources/SwiftParser/Expressions.swift [hunk 5]
```diff
@@ -917,16 +919,37 @@ extension Parser {
...
+
+      if let openDelimiter = openDelimiter {
+        return RawTokenSyntax(
+          kind: .rawStringDelimiter,
+          text: openDelimiter.tokenText,
+          leadingTriviaPieces: [],
+          trailingTriviaPieces: [],
+          presence: .missing,
+          arena: arena
+        )
```
Comment (ahoppen) [inline Sources/SwiftParser/Expressions.swift:944]: You could use
```suggestion
        return RawTokenSyntax(
          missing: .rawStringDelimiter,
          text: openDelimiter.tokenText,
          arena: arena
        )
```

If you add `text: SyntaxText? = nil,` to `RawTokenText.init(missing:arena:)` and apply the following change in the initializer.
```diff
- text: kind.defaultText ?? "",
+ text: text ?? kind.defaultText ?? "",
```

I think I’ve got at least two branches locally that do this as well…

File: Sources/SwiftParser/Expressions.swift [hunk 6]
```diff
@@ -917,16 +919,37 @@ extension Parser {
...
+      }
+
+      return nil
+    }()
```
Comment (ahoppen) [inline Sources/SwiftParser/Expressions.swift:948]: I’m personally not a huge fan of declaring a closure that you immediately call. I would prefer a paradigm like

```
let closeDelimiter: RawTokenSyntax?
if let parsedDelimiter = self.parseStringLiteralDelimiter(…) {
  closeDelimiter = parsedDelimiter
} else if let openDelimiter = openDelimiter {
  closeDelimiter = RawTokenSyntax(… missing ...)
} else {
  closeDelimiter = nil
}
```

That matches the style we use in the rest of the parser.

File: Tests/SwiftParserTest/Expressions.swift (hunk 4 above)
Comment (ahoppen) [reply Tests/SwiftParserTest/Expressions.swift:316]: I think you can just use a single marker in these tests because the two you have resolve to the same location currently.
```suggestion
      #"#^DIAG^#
```

If you name it `DIAG`, you also don’t need to specify the maker name in `DiagnosticSpec`.

**Review by ahoppen — COMMENTED** [review]
Thanks for fixing these issues. The PR looks good, I’ve got a few stylistic comments.

File: Sources/SwiftParser/Expressions.swift (hunk 5 above)
Comment (omochi) [reply Sources/SwiftParser/Expressions.swift]: Actually I looked for `RawTokenText(missing:text:arena:)` first time 😄.
I added `text:` and changed to use it.

File: Sources/SwiftParser/Expressions.swift (hunk 6 above)
Comment (omochi) [reply Sources/SwiftParser/Expressions.swift]: Sorry I didn't check style well.
I changed it not to use closure.

File: Tests/SwiftParserTest/Expressions.swift (hunk 4 above)
Comment (omochi) [reply Tests/SwiftParserTest/Expressions.swift]: I changed to share single `#^DIAG^#`.

**Comment by omochi** [comment]
@ahoppen Thanks for review. I changed styles to follow comments.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by ahoppen — APPROVED** [review]
Thanks for your fixes to the parser 👍
