### PR TITLE
adjust Indentation Of Freestanding Macro

### LINKED ISSUE #2473: Incorrect indentation added to macro that doesn’t start on a new line
The following new test case fails.

```swift
public struct TestMacro: ExpressionMacro {
  public static func expansion(of node: some FreestandingMacroExpansionSyntax, in context: some MacroExpansionContext) throws -> ExprSyntax {
    return "1"
  }
}

func testMacroAsArgument() {
  assertMacroExpansion("""
  func test() {
    print(#test)
  }
  """, expandedSource: """
  func test() {
    print(1)
  }
  """, macros: ["test": TestMacro.self])
}
```

Instead, it produces `print( 1)`, adding the indentation of the `print` line to the macro expansion.

### PR DESCRIPTION
**Pull request by vinu-vanjari**
Resolves #2473 

---

#### Summary:
- added private function `adjustIndentationOfFreestandingMacro` which extracts the same indentation logic as before, plus removes first line indentation if macro is in middle of any line. This is required as line indentation does not make sense if macro is not present at the beginning of the line.
  - eg. `print(#function)` used to produce `print(  "f(a:_:c:)")` with extra indentation after `(`. Now it should produce `print("f(a:_:c:)")`

- corrected existing unit tests + added similar tests for multi line macro expansion so that we make sure indentation is correct on large macros as well even if they are used in middle of the line 

---

#### Update:
- `adjustIndentationOfFreestandingMacro` adds appropriate indentation to expanded code. Then removes indentation of first line of expanded code (if any). Then adds exact same trivia as # macro, including it's original indentation. 
- Hence removing extra indentation from the expanded code itself and not from leading trivia of # macro node
- Added more test cases with comments with the # macro which were failing earlier

### CODE REVIEW

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 1]
```diff
@@ -131,13 +124,29 @@ private func expandFreestandingExpr(
...
+
+  var indentedSource =
+    expandedCode
+    .indented(by: indentationOfFirstLine)
+    .wrappingInTrivia(from: node)
+
+  // if the experssion started in middle of the line, then remove indentation of the first line
+  if !node.leadingTrivia.contains(where: \.isNewline) {
+    indentedSource.removeFirst(indentationOfFirstLine.sourceLength.utf8Length)
+  }
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:145]: I think this might be incorrect if `wrappingInTrivia` adds something (like a comment) because then the first `indentationOfFirstLine.sourceLength.utf8Length` characters in `indentedSource` aren’t actually the indentation but whatever `wrappingInTrivia` added.

So, this probably needs to be done before calling `wrappingInTrivia`.

**Review by ahoppen — COMMENTED** [review]
Thanks for fixing this @vinu-vanjari!

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift (hunk 1 above)
Comment (vinu-vanjari) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift]: Thanks for noticing and letting me know. I have updated the logic and added some unit tests where `wrappingInTrivia` will have comment trivia.

Please review again.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 2]
```diff
@@ -131,13 +124,29 @@ private func expandFreestandingExpr(
...
+private func adjustIndentationOfFreestandingMacro(expandedCode: String, node: some FreestandingMacroExpansionSyntax) -> String {
+  let indentationOfFirstLine = node.indentationOfFirstLine
+
+  var indentedSource =
+    expandedCode
+    .indented(by: indentationOfFirstLine)
+
+  if indentedSource.count >= indentationOfFirstLine.sourceLength.utf8Length {
+    indentedSource.removeFirst(indentationOfFirstLine.sourceLength.utf8Length)
+  }
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:143]: Am I missing something or does this check not make any sense? Previously you were checking `!node.leadingTrivia.contains(where: \.isNewline)`, which made sense to me but AFAICT this check is always satisfied because `indentedSource` has at least as many characters as the indentation of its first line.

Comment (vinu-vanjari) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:143]: since we have
```
func indented(by indentation: Trivia) -> String {
    if isEmpty || indentation.isEmpty {
      return self
    }
    // so on.. 
```
when `expandedCode` is empty string, it returns empty string and calling `removeFirst(n)` causes a crash. [Test `testErrorExpansion()` crashes because of this]

---

about previous condition, I am using different approach altogether now 😅 , so this condition is not replacement of previous one.

now we are indenting the entire expanded code first and then un-indenting the first line (with removeFirst())
then we are wrapping the expanded code in macro's trivia.

Notice that, now `wrappingInTrivia(from:)` does not remove indentation on last line. It simply adds entire trivia of macro to expanded code as it is.

So, previously we were removing indentation on last line from macro's trivia and now we are removing indentation from first line on expanded indented code

---

Here are couple of examples, (assume numbers are spaces)
|Step|Single line macro| Multi line macro|
|--|--|--|
|expanded code | `"expanded_code"` | `{\n"expanded_code"\n}`
|indent the entire code | `12"expanded_code"` | `12{\n1234"expanded_code"\n12}`
|remove first line indentation| `"expanded_code"` | `{\n1234"expanded_code"\n12}`
|adding exact same trivia as macro node at new line| `12"expanded_code"` | `12{\n1234"expanded_code"\n12}`
|or adding exact same trivia as macro in middle of the line | `"expanded_code"` | `{\n1234"expanded_code"\n12}`

Comment (ahoppen) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:143]: Oh, I see. I forgot that we would essentially add the indentation of the first line again from `wrappingInTrivia`. Could you add a short version of that explanation as a comment for anyone else who reads this in the future?

**Review by ahoppen — APPROVED** [review]
Nice. Thanks for adding the comment.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by vinu-vanjari** [comment]
@ahoppen, sorry I missed formatting in my latest commit. Just fixed it now. 🙏🏼

**Comment by ahoppen** [comment]
No worries, let’s try again.

@swift-ci Please test

**Comment by vinu-vanjari** [comment]
Kindly help, I am not able to understand root cause of the CI failure.

As per console logs,
```
/Users/ec2-user/jenkins/workspace/swift-syntax-PR-macOS/branch-main/swift-syntax/Examples/Tests/MacroExamples/Implementation/ComplexMacros/DictionaryIndirectionMacroTests.swift:13:8: error: no such module 'MacroExamplesImplementation'
import MacroExamplesImplementation
       ^
note: module 'MacroExamplesImplementation' is a macro, and cannot be imported by tests and other targets
error: fatalError
Error: Command failed with non-zero exit code 1:
```

but i am not sure if my changes affected `MacroExamplesImplementation`

**Comment by Matejkob** [comment]
> Kindly help, I am not able to understand root cause of the CI failure.
> 
> As per console logs,
> 
> ```
> /Users/ec2-user/jenkins/workspace/swift-syntax-PR-macOS/branch-main/swift-syntax/Examples/Tests/MacroExamples/Implementation/ComplexMacros/DictionaryIndirectionMacroTests.swift:13:8: error: no such module 'MacroExamplesImplementation'
> import MacroExamplesImplementation
>        ^
> note: module 'MacroExamplesImplementation' is a macro, and cannot be imported by tests and other targets
> error: fatalError
> Error: Command failed with non-zero exit code 1:
> ```
> 
> but i am not sure if my changes affected `MacroExamplesImplementation`

The CI error is not related to your changes. It should be fix after merging this PR: https://github.com/apple/swift-package-manager/pull/7349

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7350 instead of https://github.com/apple/swift-package-manager/pull/7349 should've fixed CI issues, as it clearly fixes the test build error for me locally. I'm currently investigating why the error persists on CI, as I hope we can avoid merging the revert and get this fixed properly.

**Comment by Matejkob** [comment]
> [apple/swift-package-manager#7350](https://github.com/apple/swift-package-manager/pull/7350) instead of [apple/swift-package-manager#7349](https://github.com/apple/swift-package-manager/pull/7349) should've fixed CI issues, as it clearly fixes the test build error for me locally. I'm currently investigating why the error persists on CI, as I hope we can avoid merging the revert and get this fixed properly.

Oh, sorry for the misleading info, didn't go throw the new conversation in the PR since yesterday

**Comment by MaxDesiatov** [comment]
@swift-ci clean test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7352
@swift-ci test
