### PR TITLE
[Keypath parsing] Handle space after `\` and operators ending in `.`.

### LINKED ISSUE #888: KeyPath with space produces a diagnostic
### Issue Kind

Parse of Valid Source Produced Invalid Syntax Tree

### Source Code

```swift
_ = distinctUntilChanged(\ .?.status)
```

### Description

The `\ .?.status` keypath should be parsed as a keypath, just like `\.?.status` would be.

Currently producing a diagnostic with 4f2e1537f39583f635d4a343128749d650157537:

> unexpected text '.?.status' in function call

### PR DESCRIPTION
**Pull request by DougGregor**
Fixes #888 and rdar://100871146.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

File: Tests/SwiftParserTest/Expressions.swift [hunk 1]
```diff
@@ -179,6 +179,13 @@ final class ExpressionTests: XCTestCase {
       \Optional.?!?!?!?.??!
       """#
     )
+
+    AssertParse(
+      #"""
+      _ = distinctUntilChanged(\ .?.status)
+      _ = distinctUntilChanged(\.?.status)
```
Comment (bnbarham) [inline Tests/SwiftParserTest/Expressions.swift:186]: Worth checking the structure here? Could even minimize to just `\.?.status` since the issue was just not parsing the key path correctly. There's a `swift-parser-cli debug-init-call` mode now.

Comment (DougGregor) [reply Tests/SwiftParserTest/Expressions.swift:186]: I dunno, we'll have diagnostics if anything goes amiss.
