### PR TITLE
Suggest to add missing `equal` token to variable declarations

### LINKED ISSUE #1610: Bad diagnostic for let foo: [Int] []
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
let foo: [Int] []
```

### Description

This currently produces the following. We should be suggesting to add a `=` if a variable declaration is followed by an expression on the same line without a `=` in between.

```
1 │ let foo: [Int] []
  │               ╰─ error: consecutive statements on a line must be separated by ';'
```

rdar://108623515

### PR DESCRIPTION
**Pull request by whiteio**
When a variable declaration is followed by an expression on the same line, it should be suggested to insert an `equal` token.

Resolves #1610

### CODE REVIEW

File: Sources/SwiftParser/Declarations.swift [hunk 1]
```diff
@@ -1405,6 +1407,14 @@ extension Parser {
             value: initExpr,
             arena: self.arena
           )
+        } else if self.atStartOfExpression() && !isProbablyVarDecl && !self.at(.leftBrace) && !self.currentToken.flags.contains(.isAtStartOfLine) {
```
Comment (ahoppen) [inline Sources/SwiftParser/Declarations.swift:1410]: Can’t you just inline `isProbablyVarDecl` here? If you can, you could merge the `!self.at(.leftBrace)` check into it?

Also, instead of checking `self.currentToken.flags.contains(.isAtStartOfLine)` it’s nicer to check 
```swift
self.at(TokenSpec(.identifier, allowAtStartOfLine: false), TokenSpec(.wildcard, allowAtStartOfLine: false))`
```

Also: What do we need the `isProbablyVarDecl` check for?

**Review by ahoppen — COMMENTED** [review]
Thanks @whiteio. I’ve got one question regarding the implementation. Also: Could you add a test case from the example in the issue?

File: Sources/SwiftParser/Declarations.swift (hunk 1 above)
Comment (whiteio) [reply Sources/SwiftParser/Declarations.swift]: @ahoppen Yes I've added in the test case from the example in the issue. `isProbablyVarDecl` can be inlined, I've inlined it and merged in `!self.at(.leftBrace)`.

> self.at(TokenSpec(.identifier, allowAtStartOfLine: false), TokenSpec(.wildcard, allowAtStartOfLine: false))`

Would this also need to include keywords? For example, if I change it to the above it would suggest inserting an '=' if the variable declaration is followed by an initializer on a new line, such as:
```swift
struct S {
  let _value: Int
                 ╰─ error: expected '=' in variable
  init() {
  }
}
```


> Also: What do we need the isProbablyVarDecl check for?

I added this in to make sure that the correct fixits are suggested when there are consecutive variable declarations on the same line.

For example, without the isProbablyVarDecl check it would suggest adding an '=' instead of a ';' before 'i' in the following case
```swift
let x: Int i = 10
```

Comment (ahoppen) [reply Sources/SwiftParser/Declarations.swift]: > `self.at(TokenSpec(.identifier, allowAtStartOfLine: false), TokenSpec(.wildcard, allowAtStartOfLine: false))`

I am sorry, I missed that you had a negation in front of `self.at`. Forget what I said.

> I added this in to make sure that the correct fixits are suggested when there are consecutive variable declarations on the same line.

Hmm. But this also means that you don’t generate the diagnostic to add the missing `=` if you write the following, right?

```swift
let x: Int i
```

I’m not sure if it’s really beneficial to optimize for the case where someone incorrectly writes two variable declarations on the same line. Declaring two variables on the same line isn’t very common in Swift in my experience.

Comment (whiteio) [reply Sources/SwiftParser/Declarations.swift]: > So: My take on this would be to just remove
>!self.at(.identifier, .wildcard, .leftBrace), !self.peek().rawTokenKind.is(.colon, .equal, .comma)


Yes, you're right. I've made your suggested change to remove this, I've added `!self.at(.leftBrace)` as it's needed for scenarios such as the one you've mentioned. 👍

File: Tests/SwiftParserTest/translated/ConsecutiveStatementsTests.swift [hunk 2]
```diff
@@ -102,8 +102,7 @@ final class ConsecutiveStatementsTests: XCTestCase {
           // Errors
           i = j
           j = i
-          let r : Int
-          i = j
+          let r : Int i = j
```
Comment (ahoppen) [inline Tests/SwiftParserTest/translated/ConsecutiveStatementsTests.swift:105]: Am I missing something or do you know why we aren’t interesting a `=` after `Int` as the Fix-It says?

Comment (whiteio) [reply Tests/SwiftParserTest/translated/ConsecutiveStatementsTests.swift]: Looks like `"insert '='"` wasn't included in the `applyFixits` parameter. I've added it in now.

Comment (ahoppen) [reply Tests/SwiftParserTest/translated/ConsecutiveStatementsTests.swift]: Oh, that makes sense.

File: Tests/SwiftParserTest/translated/RecoveryTests.swift [hunk 3]
```diff
@@ -78,11 +78,10 @@ final class RecoveryTests: XCTestCase {
           message: "unexpected code in function"
         ),
       ],
-      applyFixIts: ["insert '>'", "insert newline", "insert expression"],
+      applyFixIts: ["insert '>'", "insert expression"],
```
Comment (ahoppen) [inline Tests/SwiftParserTest/translated/RecoveryTests.swift:81]: The idea is that the `a` test inserts newline and the `b` test below adds the `;`. So, I think you should be able to remove `testRecovery7b`.

**Review by ahoppen — COMMENTED** [review]
Just one more comment, then we’re ready to 🚢

File: Tests/SwiftParserTest/translated/RecoveryTests.swift (hunk 3 above)
Comment (whiteio) [reply Tests/SwiftParserTest/translated/RecoveryTests.swift]: Ok, that's it removed now.

**Review by ahoppen — APPROVED** [review]
Thank you @whiteio.

**Comment by ahoppen** [comment]
@swift-ci Please test
