### PR TITLE
Add fixed source to `assertMacroExpansion`

### LINKED ISSUE #2015: Add a `fixedSource` parameter to `assertMacroExpansion`
The `assertParse` function has a `fixedSource` parameter to check that the application of Fix-Its produces valid results and it has been a valuable tool so far. `assertMacroExpansion` could gain the same parameter to check that the macro’s Fix-Its work as expected.

### PR DESCRIPTION
**Pull request by kimdv**
Resolves #2015

### CODE REVIEW

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 1]
```diff
@@ -254,16 +254,24 @@ func assertDiagnostic(
...
   _ originalSource: String,
   expandedSource expectedExpandedSource: String,
   diagnostics: [DiagnosticSpec] = [],
   macros: [String: Macro.Type],
+  applyFixIts: [String]? = nil,
+  fixedSource expectedFixedSource: String? = nil,
   testModuleName: String = "TestModule",
   testFileName: String = "test.swift",
   indentationWidth: Trivia = .spaces(4),
+  options: AssertParseOptions = [],
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:274]: I would prefer not to expose `AssertParseOptions` for now. It’s always easier to add public API in the future and I don’t think it’s newline normalization is needed to test macros in 99% of all cases. And since we don’t have substructure testing, `substructureCheckTrivia` is irrelevant here as well.

**Comment by ahoppen** [comment]
CC @bnbarham I would appreciate your review on this as well.

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 2]
```diff
@@ -254,16 +254,24 @@ func assertDiagnostic(
 ///   - macros: The macros that should be expanded, provided as a dictionary
 ///     mapping macro names (e.g., `"stringify"`) to implementation types
 ///     (e.g., `StringifyMacro.self`).
+///   - applyFixIts: Applies only the fix-its with these messages.
+///     Ohterwise all Fix-Its from diagnostics will be applied.
```
Comment (bnbarham) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:258]:
```suggestion
///     Otherwise all Fix-Its from diagnostics will be applied.
```

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 3]
```diff
@@ -254,16 +254,24 @@ func assertDiagnostic(
...
+///   - fixedSource: Asserts that the source after applying fix-its matches
```
Comment (bnbarham) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:259]:
```suggestion
///   - fixedSource: The source code to expect after applying the Fix-Its matching `applyFixIts`.
```

**Comment by bnbarham** [comment]
Thanks for doing this @kimdv 🙇 !

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift (hunk 3 above)
Comment (kimdv) [reply Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:259]: After added this comment, I tought that `Ohterwise all Fix-Its from diagnostics will be applied.` didn't make sense. 
So tried to make it a bit more explicit. 

Can you prof read again?

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 4]
```diff
@@ -254,13 +254,19 @@ func assertDiagnostic(
 ///   - macros: The macros that should be expanded, provided as a dictionary
 ///     mapping macro names (e.g., `"stringify"`) to implementation types
 ///     (e.g., `StringifyMacro.self`).
+///   - applyFixIts: The source code to expect after applying the Fix-Its matching `applyFixIts`.
+///     If none Fix-Its is provided all Fix-Its from the diagnostics will be applied.
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:258]:
```suggestion
///   - applyFixIts: If specified, filters the Fix-Its that are applied to generate `fixedSource` to only those whose message occurs in this array. If `nil`, all Fix-Its from the diagnostics are applied.
```

File: Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift [hunk 5]
```diff
@@ -254,13 +254,19 @@ func assertDiagnostic(
...
+///   - fixedSource: Asserts that the source after applying fix-its matches
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift:259]:
```suggestion
///   - fixedSource: If specified, asserts that the source code after applying Fix-Its matches this string.
```

**Review by ahoppen — COMMENTED** [review]
As always, I have some comments on documentation 😉

**Review by ahoppen — COMMENTED** [review]
Oh, sorry for not mentioning this earlier. But it would be good to have a test case that exercises `fixedSource`. I don’t think any macro in `MacroSystemTests.swift` is currently a good candidate for Fix-Its, so it’s probably easiest if you write a new macro in there.

File: Tests/SwiftSyntaxMacroExpansionTest/MacroSystemTests.swift [hunk 6]
```diff
@@ -284,9 +284,37 @@ public struct AddCompletionHandler: PeerMacro {
...
+          "can only add a completion-handler variant to an 'async' function"
+        ),
+        fixIts: [
+          FixIt(
+            message: MacroExpansionFixItMessage(
+              "add 'async'"
+            ),
+            changes: [
+              FixIt.Change.replace(
+                oldNode: Syntax(funcDecl.signature),
```
Comment (kimdv) [inline Tests/SwiftSyntaxMacroExpansionTest/MacroSystemTests.swift:308]: I don't understand why. 
But when doing this the node.id changes. 

When debugging it first get 
```
▿ SyntaxIdentifier
  - rootId : 4320226936
  ▿ indexInTree : SyntaxIndexInTree
    - indexInTree : 8
```

And when printing inside the FixItApplier I get this
```
▿ SyntaxIdentifier
  - rootId : 105553162409640
  ▿ indexInTree : SyntaxIndexInTree
    - indexInTree : 7
```

**Review by ahoppen — COMMENTED** [review]
One of the issues why you needed to add `transferTrivia: false` was that we did `nodes.map { .makeMissing(…) }`. This caused us to transfer the trivia for each token individually. Conceptually, what we want to do is to make a list of node missing and only transfer the leading trivia at the first node in the array and the trailing trivia of the last element of the array. To fix this, we should have a `makeMissing` function that takes an array of `Syntax`.

If we choose to not transfer trivia of one token, we should generally set it as the leading and trailing trivia of the newly inserted token. That way, we don’t drop it.

The reason why you needed to do `.with(\.trailingTrivia, [])` in `visit(AvailabilityConditionSyntax)` is that without it we truly have overlapping edits in `testAvailabilityQueryUnavailability34b`. `FixItApplier` checks if any of the edits intersect. If they do, we can only keep one of the edits. I would suggest that we choose to keep the larger edit. Currently we only have the `Ensure edits are not overlapping:` comment but don’t actually check that the edits are not overlapping.

I would like to split the change that updates `FixItApplier` from the change that adds `fixedSource` to `assertMacroExpansion`. That way we can merge the larger refactoring of rewriting `FixItApplier` independently of changing the public API. When you do change `assertMacroExpansion`, could you add it to the release notes?

**Comment by ahoppen** [comment]
Oh, and here’s a suggested diff for the first two points in my review

<details><summary>Diff</summary>
<p>

```diff
diff --git a/Sources/SwiftParserDiagnostics/DiagnosticExtensions.swift b/Sources/SwiftParserDiagnostics/DiagnosticExtensions.swift
index 27fb25cc..2982e9bb 100644
--- a/Sources/SwiftParserDiagnostics/DiagnosticExtensions.swift
+++ b/Sources/SwiftParserDiagnostics/DiagnosticExtensions.swift
@@ -48,6 +48,7 @@ extension FixIt {
 
 extension FixIt.MultiNodeChange {
   /// Replaced a present token with a missing node.
+  ///
   /// If `transferTrivia` is `true`, the leading and trailing trivia of the
   /// removed node will be transferred to the trailing trivia of the previous token.
   static func makeMissing(_ token: TokenSyntax, transferTrivia: Bool = true) -> Self {
@@ -55,21 +56,13 @@ extension FixIt.MultiNodeChange {
   }
 
   /// Replace present tokens with missing tokens.
-  /// If `transferTrivia` is `true`, the leading and trailing trivia of the
-  /// removed node will be transferred to the trailing trivia of the previous token.
+  ///
+  /// If `transferTrivia` is `true`, the leading trivia of the first token and
+  /// the trailing trivia of the last token will be transferred to their adjecent
+  /// tokens.
   static func makeMissing(_ tokens: [TokenSyntax], transferTrivia: Bool = true) -> Self {
-    precondition(!tokens.isEmpty)
     precondition(tokens.allSatisfy({ $0.isPresent }))
-    var changes = tokens.map {
-      FixIt.Change.replace(
-        oldNode: Syntax($0),
-        newNode: Syntax($0.with(\.presence, .missing))
-      )
-    }
-    if transferTrivia {
-      changes += FixIt.MultiNodeChange.transferTriviaAtSides(from: tokens).primitiveChanges
-    }
-    return FixIt.MultiNodeChange(primitiveChanges: changes)
+    return .makeMissing(tokens.map(Syntax.init), transferTrivia: transferTrivia)
   }
 
   /// If `transferTrivia` is `true`, the leading and trailing trivia of the
@@ -104,6 +97,25 @@ extension FixIt.MultiNodeChange {
       return FixIt.MultiNodeChange()
     }
   }
+
+  /// Replace present nodes with their missing equivalents.
+  ///
+  /// If `transferTrivia` is `true`, the leading trivia of the first node and
+  /// the trailing trivia of the last node will be transferred to their adjecent
+  /// tokens.
+  static func makeMissing(_ nodes: [Syntax], transferTrivia: Bool = true) -> Self {
+    precondition(!nodes.isEmpty)
+    var changes = nodes.map {
+      FixIt.Change.replace(
+        oldNode: $0,
+        newNode: MissingMaker().rewrite($0, detach: true)
+      )
+    }
+    if transferTrivia {
+      changes += FixIt.MultiNodeChange.transferTriviaAtSides(from: nodes).primitiveChanges
+    }
+    return FixIt.MultiNodeChange(primitiveChanges: changes)
+  }
 }
 
 // MARK: - Make present
diff --git a/Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift b/Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift
index 629d91a0..574c800a 100644
--- a/Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift
+++ b/Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift
@@ -182,7 +182,7 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
       correctToken.isMissing
     {
       // We are exchanging two adjacent tokens, transfer the trivia from the incorrect token to the corrected token.
-      changes += misplacedTokens.map { FixIt.MultiNodeChange.makeMissing($0, transferTrivia: false) }
+      changes += [FixIt.MultiNodeChange.makeMissing(misplacedTokens, transferTrivia: false)]
       changes.append(
         FixIt.MultiNodeChange.makePresent(
           correctToken,
@@ -772,7 +772,7 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
             message: ReplaceTokensFixIt(replaceTokens: [token], replacements: [.commaToken()]),
             changes: [
               .makeMissing(token, transferTrivia: false),
-              .makePresent(trailingComma),
+              .makePresent(trailingComma, leadingTrivia: token.leadingTrivia, trailingTrivia: token.trailingTrivia),
             ]
           )
         ],
@@ -813,7 +813,7 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
         fixIts: [
           FixIt(
             message: RemoveNodesFixIt(nodes),
-            changes: nodes.map { .makeMissing($0, transferTrivia: !node.deinitKeyword.trailingTrivia.contains(where: { $0.isWhitespace })) }
+            changes: .makeMissing(nodes)
           )
         ],
         handledNodes: nodes.map { $0.id }
@@ -1537,7 +1537,7 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
         fixIts: [
           FixIt(
             message: RemoveNodesFixIt(rawDelimiters),
-            changes: rawDelimiters.map { .makeMissing($0) }
+            changes: .makeMissing(rawDelimiters)
           )
         ],
         handledNodes: rawDelimiters.map { $0.id }
@@ -1858,7 +1858,7 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
             ),
             changes: [
               .makeMissing(equalToken, transferTrivia: false),
-              .makePresent(node.colon),
+              .makePresent(node.colon, leadingTrivia: equalToken.leadingTrivia, trailingTrivia: equalToken.trailingTrivia),
             ]
           )
         ],
@@ -1966,8 +1966,9 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
             FixIt(
               message: fixItMessage,
               changes: [
-                FixIt.MultiNodeChange.makePresent(detail.detail)
-              ] + unexpectedTokens.map { .makeMissing($0, transferTrivia: false) }
+                FixIt.MultiNodeChange.makePresent(detail.detail),
+                .makeMissing(unexpectedTokens)
+              ]
             )
           ],
           handledNodes: [detail.id] + unexpectedTokens.map(\.id)
```

</p>
</details>

File: Release Notes/511.md [hunk 7]
```diff
@@ -2,6 +2,11 @@
 
 ## New APIs
 
+- `assertMacroExpansion` now have new parameters named `fixedSource` and `fixedSource`
+  - Description: `fixedSource` and `fixedSource` are used to assert so ensure that the source code after applying Fix-Its matches this string.
```
Comment (bnbarham) [inline Release Notes/511.md:6]: I'm not crazy and these do both say `fixedSource` right 😅? I assume this is meant to be `applyFixIts`?

Comment (kimdv) [reply Release Notes/511.md]: You are right! 🤦‍♂️

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@bnbarham sorry for the delay! 
I think it should be ready now

**Review by ahoppen — APPROVED** [review]

File: Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift [hunk 8]
```diff
@@ -193,4 +221,30 @@ final class PeerMacroTests: XCTestCase {
...
+          message: "can only add a completion-handler variant to an 'async' function",
+          line: 2,
+          column: 1,
+          fixIts: [FixItSpec(message: "add 'async'")]
+        )
+      ],
+      macros: ["addCompletionHandler": AddCompletionHandler.self],
+      fixedSource: """
+        @addCompletionHandler
+        func f(a: Int, for b: String, _ value: Double) async-> String { }
```
Comment (bnbarham) [inline Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift:245]: I assume we don't care about adding the proper trivia just in this test case? Though FWIW the completion handler macro seems like a fairly beefy macro to have in our tests in general.

**Review by bnbarham — APPROVED** [review]

File: Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift (hunk 8 above)
Comment (kimdv) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift:245]: Should I make a smaller macro? 

The idea is to have a more real-show case in a test case, so developers can see an example and what the expected result is

Comment (bnbarham) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift:245]: Examples seem like they would be better off living in the examples. The test should be the minimum of whatever we want to test. I don't really mind if you want to leave it for now (it was already there as far as I can tell), this was more of an off hand comment.

Having said that, if the idea is that this is an example, then that would presumably imply that we do care about the missing trivia 😅

Comment (kimdv) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: @bnbarham @ahoppen I've tried to reduce the test case. 
Should I try to reduce it more. It's properly not a valid real scenario, but it does the job in test I think

Comment (ahoppen) [reply Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift]: Am I missing something or are you no longer adding a `fixedSource` parameter anymore? As it stands right now, I’m pretty sure the test will fail because we are no longer adding the completion handler.

What I would suggest is that we keep the completion handler test case for now because I’m not sure if it tests anything that’s not covered by the other peer macro test cases and you add the test that you wrote as a new test case that is intended to test the `fixedSource`.

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Review by Matejkob — COMMENTED** [review]
Hi there!

I've been integrating the new functionality of the `assertMacroExpansion` function into our macro examples and I've run into a few issues:

1. It's not a major concern, but the `AddCompletionHandler` macro from the unit tests fails to compile when used in regular code. Although it's only a test case, I think it would be beneficial for it to produce valid Swift code. The issue arises here: https://github.com/apple/swift-syntax/blob/098b177830c0d2e614b3757241b2572d758f9143/Tests/SwiftSyntaxMacroExpansionTest/PeerMacroTests.swift#L85, where the closure would be called from `Task`, resulting in the error `Escaping closure captures non-escaping parameter 'completionHandler'`.

2. We have the following test case:

```swift
func testExpansionOnNonAsyncFunctionAppliesFixIt() {
  assertMacroExpansion(
    """
    struct Test {
      @AddCompletionHandler
      func fetchData() -> String {
        return "Hello, World!"
      }
    }
    """,
    expandedSource: """
      struct Test {
        func fetchData() -> String {
          return "Hello, World!"
        }
      }
      """,
    diagnostics: [
      DiagnosticSpec(
        message: "can only add a completion-handler variant to an 'async' function",
        line: 3,
        column: 3,
        severity: .error,
        fixIts: [FixItSpec(message: "add 'async'")]
      )
    ],
    macros: macros,
    applyFixIts: ["add 'async'"],
    fixedSource: """
    struct Test {
      @AddCompletionHandler
      func fetchData() async -> String {
        return "Hello, World!"
      }
    }
    """,
    indentationWidth: .spaces(2)
  )
}
```

The expected fixed source is:

```swift
struct Test {
  @AddCompletionHandler
  func fetchData() async -> String {
    return "Hello, World!"
  }
}
```

However, the actual result is:
Screenshot 2023-11-05 at 4 42 29 PM

This is clearly an issue on our end because the compiler is correctly applying the fix-it.

3. I'm considering whether we should still assert the `expandedSource` against the expansion before applying any fix-its, even after using the `applyFixIts` parameter in the `assertMacroExpansion` function. A comprehensive test case for clients could look like this: the user provides the `originalSource` containing an error, then the assert function applies the fix-it and attempts to expand the corrected source code. @mbrandonw and @stephencelis have implemented a similar approach in their `swift-macro-testing` tool, which can be found here: https://github.com/pointfreeco/swift-macro-testing/blob/35acd9468d40ae87e75991a18af6271e8124c261/README.md?plain=1#L148-L188. Reflecting on this further, I believe `expandedSource` should remain unchanged and we might consider adding a new parameter—`expandedSourceAfterApplyingFixIt`—to allow users to provide the expanded code post-fix-it application. This is important since a macro can offer a fix-it associated with a diagnostic of a severity other than `error`, and the expansion process can proceed regardless of the fix-it.

**Comment by ahoppen** [comment]
> 1. It's not a major concern, but the AddCompletionHandler macro from the unit tests fails to compile when used in regular code.

I don’t have strong opinions on this one. It is only a test case to test that peer macros work on a syntactical level and for me it’s OK if the generated code has semantic issues. As the comment on the top of the file says

> The macros defined in this file are intended to test the behavior of MacroSystem. Many of them do not serve as good examples of how macros should be written. In particular, they often lack error handling because it is not needed in the few test cases in which these macros are invoked.

---

> 2. We have the following test case. […] The expected fixed source is […]However, the actual result is […] This is clearly an issue on our end because the compiler is correctly applying the fix-it.

Oh, could you file an issue?

---

> 3. I'm considering whether we should still assert the `expandedSource` against the expansion before applying any fix-its, even after using the `applyFixIts` parameter in the `assertMacroExpansion` function.

That does sound reasonable to me. Would you like to open a PR with the change? We can discuss the details on that PR.

**Comment by Matejkob** [comment]
> > 2. We have the following test case. […] The expected fixed source is […]However, the actual result is […] This is clearly an issue on our end because the compiler is correctly applying the fix-it.
> 
> Oh, could you file an issue?
> 

I'm on it. 

> > 3. I'm considering whether we should still assert the `expandedSource` against the expansion before applying any fix-its, even after using the `applyFixIts` parameter in the `assertMacroExpansion` function.
> 
> That does sound reasonable to me. Would you like to open a PR with the change? We can discuss the details on that PR.

I'm on it.
